version: '3.9'

services:
  postgres:
    container_name: database
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    # volumes:
    #   - /home/kostia/fun/database/data:/var/lib/postgresql/data
    networks:
      - my_network
    restart: unless-stopped

networks:
  my_network:
    driver: bridge

